<!DOCTYPE html>
<!-- ProjectPresentation.php 
This is a comment. Comments are not displayed in the browser.
To run it as a php file:
http://localhost/BCHB697/ges43/ProjectPresentation.php/-->


<!DOCTYPE html>
<html lang="en">
<head>
  <title>Ges43_ProjectPresentation.php</title>
 
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

<div class="page-header" align="center">
    <img src="images/SCHIZOPHRENIA.jpg" style="height:60%; width:60%">
    <h1>Schizophrenia and Malaria?</h1>

</div>
<div class="container" style="background: url('images/ground.jpg') no-repeat center center fixed;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    background-size: cover;
    -o-background-size: cover;">
     <!--div align="center"></div-->
  
  <ul class="nav nav-pills nav-justified" align="center">
	  <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
	  <li class="dropdown">
	    <a class="dropdown-toggle" data-toggle="dropdown" href="#">My website documentation
	    <span class="caret"></span></a>
	    <ul class="dropdown-menu">
	      <li><a href="#PracticalApp" data-toggle="tab">Practical applications</a></li>
	      <li><a href="#DescribeData" data-toggle="tab">Data Description</a></li>
          <li><a href="#P2PUEER" data-toggle="tab">Data Model</a></li>
	      <li><a href="#WebsiteHowToDeploy" data-toggle="tab">Deployment Instructions</a></li>
	      <li><a href="#WebsiteHowToUse" data-toggle="tab">Website How-To</a></li>  
	    </ul>
	  </li>
	  <li><a href="#gsIndex" data-toggle="tab">Report Search Index</a></li>
	  <li><a href="#FutureWork" data-toggle="tab">Future Work</a></li>
  </ul>

	<div class="tab-content">
	    <div id="home" class="tab-pane fade in active">
	      <h3>HOME</h3>
    WELCOME to the GES43 Protein to Phenotype Database Application!

	    </div>
	    <div id="DescribeData" class="tab-pane fade">
	     <h3>My Bioinformatics data set</h3>
            <ul>
                <li>
                    <b>What is my data set?</b>
                    <p> This data contains UniprotKB Protein entries, along with their disease annotations, gene information from the HGNC database, and disease entries from the disease ontology database. The protein data was found by searching for proteins implicated in Malaria and Schizophrenia.
                    </p>
                </li>
                <li>
                    <b>Why did I select this data set?</b>
                    <p> By collecting this data set of protein, gene and disease information, we can look at the the protein functions affected in Malaria and Schizophrenia and analyze them for any relations, and we can similarly observe any similarities or relationships between the diseases with which protein entries are annotated.
                    </p>
                </li>
                <li>
                    <b>Where and how did I collect this data set?</b>
                    <p> Uniprot entries were generated by using the advanced search to find proteins who had pathology/biotechnology-disease annotations of Schizophrenia, and by using Malaria as a simple search term.</p>
                    <p>The record pages of some these Uniprot Entry pages contained annotations to MIM entries from which data was gathered. The MIM Entry id's were entered into the disease ontology database to find additional disease classisfication information. </p>
                    <br>
                </li>
                <li>
                    <b>What are the buisness rules or specifications of my data set?</b>
                    <p>
                        <ul>
                            <li>Multiple piece of data (rows) can be collected by a person, but a piece of data (a row) can be collected by only one person.</li>
                            <li>A targeted disease can yield multiple uniprotKB entries. A uniprotKB entry number is always unique. </li>
                            <li>A uniprot entry can correspond to multiple diseases, but in this table, to only one targeted disease.</li>
                            <li>Each uniprot entry has exactly only one uniprot url. This url can be derived from the uniprot entry number. It is unique to uniprot entry.</li>
                            <li>Each uniprot entry must have exactly one full protein name. This is unique to a uniprot entry. It is also required for any uniprot entry.</li>
                            <li>Each uniprot entry may have one set of Alternative names unique to the protein.</li>
                            <li>Each uniprot entry must have one sequence length and one mass. Multiple entries may have the same sequence length or the same mass.</li>
                            <li>Each uniprot entry must have one gene name. This is unique to a uniprot protein.</li>
                            <li>Each uniprot entry must have exactly one HGNC ID. This is unique to the entry. It is accompanied by the HGNC URL, which is derivable from the HGNC ID, and also unique to one entry.</li>
                            <li>Each uniprot entry must have a unique HGNC approved symbol and approved name. Each must also have a unique set of HGNC synonyms.</li>
                        </ul>
                    </p>
                    <p>
                        <a href="ges43_Data_Collection_model.pdf" target="_blank" ><b>Click here for a download with more details on the data</b></a>
                    </p>
                </li>
            </ul>
		</div>
        <div id="gsIndex" class="tab-pane fade">
            <h3>Report Search Index</h3>
            <p> On this page, you may find reports answering specific bioinformatics questions.
            </p>
            <ul>
            <!--li>
            <p>Test Multiquery <a href="Multiquery.php"><b>here</b></a>.</p-->
            <li><p>To get overview information on a specific protein in this database, please go <a href="gsProt_Overview.php"><b>here</b></a>.</P>
            </li>

            <li><p>To find entries of proteins that are encoded by genes on a specific chromosome, please go <a href="gsChrom_num.php"><b>here</b></a>.</P>
            </li>
            <li><p>To find protein entries that link to DO diseases of specific kind, please go <a href="gsDis_type.php"><b>here</b></a>.</p>
            </li>
            <li><p>To find entries of proteins that are have a mass within a specific range, please go <a href="gsPep_mass.php"><b>here</b></a>.</P>
            </li>
            <li><p>To find answers to prebuilt questions that are potentially asked frequently, please go <a href="gsMulti_facts.php"><b>here</b></a>.</P>
            </li>
            </ul>
        </div>
        <div id="PracticalApp" class="tab-pane fade">
            <h3> Practical Applications of this website</h3>
            <p>On this website, a series of reports can be found answering a set of bioinformatics questions.</p>
            <p>These questions can be useful for users with specific biological, protein-related questions, to allow drawing hyoptheses.</p>
            <p>For example, with knowledge of a specific type of disease that related to Schizophrenia or Malaria, or with a specific chromosome in mind, the dataset in this website can be searched for interesting results.</p>

        </div>
        <div id="P2PUEER" class="tab-pane fade">
            <h3>E-R Diagram of GES43 relational data model</h3>
            <button id="code" type="submit" class="btn btn-success" style="width:400px;"> Download here</button>
        </div>
        <div id="WebsiteHowToDeploy" class="tab-pane fade">
            <h3>Deployment Instructions</h3>
            <button id="code2" type="submit" class="btn btn-success" style="width:400px;">Found here</button>
        </div>
        <div id="WebsiteHowToUse" class="tab-pane fade">
            <h3>How-to guide for navigating website</h3>
            <button id="code3" type="submit" class="btn btn-success" style="width:400px;">Found here</button>
        </div>
        <div id="FutureWork" class="tab-pane fade">
            <h3> Future Work</h3>
            <ol>
                <li> <b>Collect Additional Data</b>
                <p> Supplement database with data collected from structural and protein interaction database
                </p></li>
                
                <li> <b>Fill in the Ggaps on Malaria</b>
                <p> This disease reports sginificantly less entries on UniprotKB than Schizophrenia; Is there research that can account for this disease? Add overview pages for Malaria and Schizophrenia, or maybe link to such a pre-existing resource. 
                </p></li>
                <li> <b>Sequence Information</b>
                <p> Being able to query accross protein or gene sequences might be of interest and use for drawing further information from the collected data.
                </p></li>
                
                <!--li> <b>(add text here)</b>
                <p> (add your sentences or supporting documents here)
                </p></li-->
            </ol>

        </div>

        <div class="container"><br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
        </div>

</div>
<script>
$('#code').click(function(){
window.open("P2PU_EER.pdf");
});
$('#code2').click(function(){
window.open("WebsiteHowToDeploy.php");
});
$('#code3').click(function(){
window.open("WebsiteHowToUse.php");
});
</script>

<!-- html lang='en'>
<head>
    <meta charset="UTF-8" /> 
    <title>
        Ges43_ProjectPresentation.php
    </title>
	<div align="center">
<img src="images/SCHIZOPHRENIA.jpg"></div>
    <link rel="stylesheet" type="text/css" HREF="StyleSheets.css">
</head>
<body class="homeP">

<div align="center">
<h1 id="homeP" style="text-align:center; color:black; "> heading 
    Schizophrenia and Malaria?
</h1>
</div>
<br>
<div style="margin:auto 430px; width:50%">
<ul style="color:black;">
	<li>
	<p><b>Presented by: Gaelle Sop-Kamga </b></p></li>
	<li>
	<p><b>Date: 04/29/2016 </b></P></li>
</ul></div>


 <br> <br>
<div align="center">
<ul>
	<li class="home"><p><a href="WebsiteDocs.php" ><b>My website documentation</b></a></p></li>
	<li class="home"><p><a href="gsIndex.php" ><b>Report Search Index</b></a></p></li>
	<li class="home"><p><a href="FutureWork.php" ><b>Future work</b></a></p></li>
</ul></div>
<br><br><br-->

</body>
</html>